# Generated by Django 3.2 on 2021-04-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='url_friendly_text',
            field=models.CharField(default='subject_name', max_length=30),
        ),
    ]
